version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - forms-api-pgdata:/var/lib/postgresql/data/
volumes:
  forms-api-pgdata: {}
